# Definindo um recurso PersistentVolumeClaim
apiVersion: v1
kind: PersistentVolumeClaim
# Metadados da solicitação de volume persistente
metadata:
  # Nome da solicitação
  name: mysql-pvc
# Especificações da solicitação de volume persistente
spec:
  # Modos de acesso
  accessModes:
    # Leitura e escrita somente uma vez
    - ReadWriteOnce
  resources:
    # Recursos solicitados
    requests:
      # Tamanho do armazenamento solicitado
      storage: 1Gi 