# Definindo um Service para o mysql
apiVersion: v1
# Tipo de objeto a ser criado
kind: Service
# Metadados do serviço
metadata:
  # Nome do serviço
  name: mysql-service
  labels:
    # Rótulo da aplicação
    app: mysql-service
# Especificação do serviço
spec:
  ports: # Portas expostas pelo serviço
  - port: 3306 # Porta externa
    targetPort: 3306 # Porta alvo do container
  selector:
    # Seletor de pods alvos
    app: mysql-db-pod # Deve corresponder ao rótulo da aplicação
  # Tipo de serviço
  type: ClusterIP
