# Definindo um recurso PersistentVolume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  # Especificando a capacidade de armazenamento
  capacity:
    storage: 1Gi
  # Modo de acesso ao armazenamento
  accessModes:
    - ReadWriteOnce
  # Política de reivindicação do volume persistente
  persistentVolumeReclaimPolicy: Delete
  # Caminho no host
  hostPath:
    path: /data/mysql-pv
  # Referencia ao PersistentVolumeClaim
  claimRef:
    name: mysql-pvc
    namespace: default
