# Definindo um recurso PersistentVolume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
# Especificando a capacidade de armazenamento
spec:
  capacity:
    storage: 1Gi
# Modo de acesso ao armazenamento
  accessModes:
    - ReadWriteOnce
# Política de reivindicação do volume persistente
  persistentVolumeReclaimPolicy: Retain
# Caminho no host
  hostPath:
    path: /data/mysql-pv
# Referencia ao PersistentVolumeClaim
  claimRef:
    name: mysql-pvc
    namespace: default
